# Site settings
title: MVC the Podcast
email: mvcthepodcast@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Marty is a computer science lecturer at Stanford and Victoria is a software engineer at Google, and together they are MVC the podcast!
  This is a podcast in which two softare engineers casually chat about this week's news in technology.
baseurl: "" # the subpath of your site, e.g. /blog/url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://mvc-the-podcast.github.io" # the base hostname & protocol for your site
github_username: mvc-the-podcast 

# Build settings
markdown: kramdown
